/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables;


import de.nightara.discord.raidbot.model.Keys;
import de.nightara.discord.raidbot.model.Raidbot;
import de.nightara.discord.raidbot.model.tables.Boss.BossPath;
import de.nightara.discord.raidbot.model.tables.Role.RolePath;
import de.nightara.discord.raidbot.model.tables.Wing.WingPath;
import de.nightara.discord.raidbot.model.tables.records.BossRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Boss extends TableImpl<BossRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raidbot.boss</code>
     */
    public static final Boss BOSS = new Boss();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BossRecord> getRecordType() {
        return BossRecord.class;
    }

    /**
     * The column <code>raidbot.boss.short_name</code>.
     */
    public final TableField<BossRecord, String> SHORT_NAME = createField(DSL.name("short_name"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>raidbot.boss.wing</code>.
     */
    public final TableField<BossRecord, String> WING = createField(DSL.name("wing"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>raidbot.boss.name</code>.
     */
    public final TableField<BossRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>raidbot.boss.after</code>.
     */
    public final TableField<BossRecord, String> AFTER = createField(DSL.name("after"), SQLDataType.VARCHAR(5).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Boss(Name alias, Table<BossRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Boss(Name alias, Table<BossRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>raidbot.boss</code> table reference
     */
    public Boss(String alias) {
        this(DSL.name(alias), BOSS);
    }

    /**
     * Create an aliased <code>raidbot.boss</code> table reference
     */
    public Boss(Name alias) {
        this(alias, BOSS);
    }

    /**
     * Create a <code>raidbot.boss</code> table reference
     */
    public Boss() {
        this(DSL.name("boss"), null);
    }

    public <O extends Record> Boss(Table<O> path, ForeignKey<O, BossRecord> childPath, InverseForeignKey<O, BossRecord> parentPath) {
        super(path, childPath, parentPath, BOSS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BossPath extends Boss implements Path<BossRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BossPath(Table<O> path, ForeignKey<O, BossRecord> childPath, InverseForeignKey<O, BossRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BossPath(Name alias, Table<BossRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BossPath as(String alias) {
            return new BossPath(DSL.name(alias), this);
        }

        @Override
        public BossPath as(Name alias) {
            return new BossPath(alias, this);
        }

        @Override
        public BossPath as(Table<?> alias) {
            return new BossPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Raidbot.RAIDBOT;
    }

    @Override
    public UniqueKey<BossRecord> getPrimaryKey() {
        return Keys.KEY_BOSS_PRIMARY;
    }

    @Override
    public List<ForeignKey<BossRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BOSS_BOSS_SHORT_NAME_FK, Keys.BOSS_WING_SHORT_NAME_FK);
    }

    private transient BossPath _boss;

    /**
     * Get the implicit join path to the <code>raidbot.boss</code> table.
     */
    public BossPath boss() {
        if (_boss == null)
            _boss = new BossPath(this, Keys.BOSS_BOSS_SHORT_NAME_FK, null);

        return _boss;
    }

    private transient WingPath _wing;

    /**
     * Get the implicit join path to the <code>raidbot.wing</code> table.
     */
    public WingPath wing() {
        if (_wing == null)
            _wing = new WingPath(this, Keys.BOSS_WING_SHORT_NAME_FK, null);

        return _wing;
    }

    private transient RolePath _role;

    /**
     * Get the implicit to-many join path to the <code>raidbot.role</code> table
     */
    public RolePath role() {
        if (_role == null)
            _role = new RolePath(this, null, Keys.ROLE_BOSS_SHORT_NAME_FK.getInverseKey());

        return _role;
    }

    @Override
    public Boss as(String alias) {
        return new Boss(DSL.name(alias), this);
    }

    @Override
    public Boss as(Name alias) {
        return new Boss(alias, this);
    }

    @Override
    public Boss as(Table<?> alias) {
        return new Boss(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Boss rename(String name) {
        return new Boss(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Boss rename(Name name) {
        return new Boss(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Boss rename(Table<?> name) {
        return new Boss(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Boss where(Condition condition) {
        return new Boss(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Boss where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Boss where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Boss where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Boss where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Boss where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Boss where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Boss where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Boss whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Boss whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
