/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables;


import de.nightara.discord.raidbot.model.Keys;
import de.nightara.discord.raidbot.model.Raidbot;
import de.nightara.discord.raidbot.model.tables.Signup.SignupPath;
import de.nightara.discord.raidbot.model.tables.Wing.WingPath;
import de.nightara.discord.raidbot.model.tables.records.RunRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Run extends TableImpl<RunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raidbot.run</code>
     */
    public static final Run RUN = new Run();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RunRecord> getRecordType() {
        return RunRecord.class;
    }

    /**
     * The column <code>raidbot.run.date</code>.
     */
    public final TableField<RunRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATE)), this, "");

    /**
     * The column <code>raidbot.run.ordinal</code>.
     */
    public final TableField<RunRecord, UInteger> ORDINAL = createField(DSL.name("ordinal"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>raidbot.run.wing</code>.
     */
    public final TableField<RunRecord, String> WING = createField(DSL.name("wing"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    private Run(Name alias, Table<RunRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Run(Name alias, Table<RunRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>raidbot.run</code> table reference
     */
    public Run(String alias) {
        this(DSL.name(alias), RUN);
    }

    /**
     * Create an aliased <code>raidbot.run</code> table reference
     */
    public Run(Name alias) {
        this(alias, RUN);
    }

    /**
     * Create a <code>raidbot.run</code> table reference
     */
    public Run() {
        this(DSL.name("run"), null);
    }

    public <O extends Record> Run(Table<O> path, ForeignKey<O, RunRecord> childPath, InverseForeignKey<O, RunRecord> parentPath) {
        super(path, childPath, parentPath, RUN);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RunPath extends Run implements Path<RunRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RunPath(Table<O> path, ForeignKey<O, RunRecord> childPath, InverseForeignKey<O, RunRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RunPath(Name alias, Table<RunRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RunPath as(String alias) {
            return new RunPath(DSL.name(alias), this);
        }

        @Override
        public RunPath as(Name alias) {
            return new RunPath(alias, this);
        }

        @Override
        public RunPath as(Table<?> alias) {
            return new RunPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Raidbot.RAIDBOT;
    }

    @Override
    public UniqueKey<RunRecord> getPrimaryKey() {
        return Keys.KEY_RUN_PRIMARY;
    }

    @Override
    public List<UniqueKey<RunRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_RUN_RUN_PK_2);
    }

    @Override
    public List<ForeignKey<RunRecord, ?>> getReferences() {
        return Arrays.asList(Keys.RUN_WING_ID_FK);
    }

    private transient WingPath _wing;

    /**
     * Get the implicit join path to the <code>raidbot.wing</code> table.
     */
    public WingPath wing() {
        if (_wing == null)
            _wing = new WingPath(this, Keys.RUN_WING_ID_FK, null);

        return _wing;
    }

    private transient SignupPath _signup;

    /**
     * Get the implicit to-many join path to the <code>raidbot.signup</code>
     * table
     */
    public SignupPath signup() {
        if (_signup == null)
            _signup = new SignupPath(this, null, Keys.SIGNUP_RUN_DATE_FK.getInverseKey());

        return _signup;
    }

    @Override
    public Run as(String alias) {
        return new Run(DSL.name(alias), this);
    }

    @Override
    public Run as(Name alias) {
        return new Run(alias, this);
    }

    @Override
    public Run as(Table<?> alias) {
        return new Run(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Run rename(String name) {
        return new Run(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Run rename(Name name) {
        return new Run(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Run rename(Table<?> name) {
        return new Run(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Run where(Condition condition) {
        return new Run(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Run where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Run where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Run where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Run where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Run where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Run where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Run where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Run whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Run whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
