/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables;


import de.nightara.discord.raidbot.model.Keys;
import de.nightara.discord.raidbot.model.Raidbot;
import de.nightara.discord.raidbot.model.tables.Role.RolePath;
import de.nightara.discord.raidbot.model.tables.Run.RunPath;
import de.nightara.discord.raidbot.model.tables.records.SignupRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Signup extends TableImpl<SignupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raidbot.signup</code>
     */
    public static final Signup SIGNUP = new Signup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SignupRecord> getRecordType() {
        return SignupRecord.class;
    }

    /**
     * The column <code>raidbot.signup.date</code>.
     */
    public final TableField<SignupRecord, LocalDate> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>raidbot.signup.role</code>.
     */
    public final TableField<SignupRecord, UInteger> ROLE = createField(DSL.name("role"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>raidbot.signup.player</code>.
     */
    public final TableField<SignupRecord, Long> PLAYER = createField(DSL.name("player"), SQLDataType.BIGINT.nullable(false), this, "");

    private Signup(Name alias, Table<SignupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Signup(Name alias, Table<SignupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>raidbot.signup</code> table reference
     */
    public Signup(String alias) {
        this(DSL.name(alias), SIGNUP);
    }

    /**
     * Create an aliased <code>raidbot.signup</code> table reference
     */
    public Signup(Name alias) {
        this(alias, SIGNUP);
    }

    /**
     * Create a <code>raidbot.signup</code> table reference
     */
    public Signup() {
        this(DSL.name("signup"), null);
    }

    public <O extends Record> Signup(Table<O> path, ForeignKey<O, SignupRecord> childPath, InverseForeignKey<O, SignupRecord> parentPath) {
        super(path, childPath, parentPath, SIGNUP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SignupPath extends Signup implements Path<SignupRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SignupPath(Table<O> path, ForeignKey<O, SignupRecord> childPath, InverseForeignKey<O, SignupRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SignupPath(Name alias, Table<SignupRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SignupPath as(String alias) {
            return new SignupPath(DSL.name(alias), this);
        }

        @Override
        public SignupPath as(Name alias) {
            return new SignupPath(alias, this);
        }

        @Override
        public SignupPath as(Table<?> alias) {
            return new SignupPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Raidbot.RAIDBOT;
    }

    @Override
    public List<ForeignKey<SignupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SIGNUP_ROLE_ID_FK, Keys.SIGNUP_RUN_DATE_FK);
    }

    private transient RolePath _role;

    /**
     * Get the implicit join path to the <code>raidbot.role</code> table.
     */
    public RolePath role() {
        if (_role == null)
            _role = new RolePath(this, Keys.SIGNUP_ROLE_ID_FK, null);

        return _role;
    }

    private transient RunPath _run;

    /**
     * Get the implicit join path to the <code>raidbot.run</code> table.
     */
    public RunPath run() {
        if (_run == null)
            _run = new RunPath(this, Keys.SIGNUP_RUN_DATE_FK, null);

        return _run;
    }

    @Override
    public Signup as(String alias) {
        return new Signup(DSL.name(alias), this);
    }

    @Override
    public Signup as(Name alias) {
        return new Signup(alias, this);
    }

    @Override
    public Signup as(Table<?> alias) {
        return new Signup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Signup rename(String name) {
        return new Signup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Signup rename(Name name) {
        return new Signup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Signup rename(Table<?> name) {
        return new Signup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Signup where(Condition condition) {
        return new Signup(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Signup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Signup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Signup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Signup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Signup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Signup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Signup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Signup whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Signup whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
