/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables;


import de.nightara.discord.raidbot.model.Keys;
import de.nightara.discord.raidbot.model.Raidbot;
import de.nightara.discord.raidbot.model.tables.Wing.WingPath;
import de.nightara.discord.raidbot.model.tables.records.WingSetRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WingSet extends TableImpl<WingSetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raidbot.wing_set</code>
     */
    public static final WingSet WING_SET = new WingSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WingSetRecord> getRecordType() {
        return WingSetRecord.class;
    }

    /**
     * The column <code>raidbot.wing_set.name</code>.
     */
    public final TableField<WingSetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>raidbot.wing_set.wing</code>.
     */
    public final TableField<WingSetRecord, String> WING = createField(DSL.name("wing"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>raidbot.wing_set.ordinal</code>.
     */
    public final TableField<WingSetRecord, Integer> ORDINAL = createField(DSL.name("ordinal"), SQLDataType.INTEGER.nullable(false), this, "");

    private WingSet(Name alias, Table<WingSetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WingSet(Name alias, Table<WingSetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>raidbot.wing_set</code> table reference
     */
    public WingSet(String alias) {
        this(DSL.name(alias), WING_SET);
    }

    /**
     * Create an aliased <code>raidbot.wing_set</code> table reference
     */
    public WingSet(Name alias) {
        this(alias, WING_SET);
    }

    /**
     * Create a <code>raidbot.wing_set</code> table reference
     */
    public WingSet() {
        this(DSL.name("wing_set"), null);
    }

    public <O extends Record> WingSet(Table<O> path, ForeignKey<O, WingSetRecord> childPath, InverseForeignKey<O, WingSetRecord> parentPath) {
        super(path, childPath, parentPath, WING_SET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WingSetPath extends WingSet implements Path<WingSetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WingSetPath(Table<O> path, ForeignKey<O, WingSetRecord> childPath, InverseForeignKey<O, WingSetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WingSetPath(Name alias, Table<WingSetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WingSetPath as(String alias) {
            return new WingSetPath(DSL.name(alias), this);
        }

        @Override
        public WingSetPath as(Name alias) {
            return new WingSetPath(alias, this);
        }

        @Override
        public WingSetPath as(Table<?> alias) {
            return new WingSetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Raidbot.RAIDBOT;
    }

    @Override
    public UniqueKey<WingSetRecord> getPrimaryKey() {
        return Keys.KEY_WING_SET_PRIMARY;
    }

    @Override
    public List<ForeignKey<WingSetRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WING_SET_WING_SHORT_NAME_FK);
    }

    private transient WingPath _wing;

    /**
     * Get the implicit join path to the <code>raidbot.wing</code> table.
     */
    public WingPath wing() {
        if (_wing == null)
            _wing = new WingPath(this, Keys.WING_SET_WING_SHORT_NAME_FK, null);

        return _wing;
    }

    @Override
    public WingSet as(String alias) {
        return new WingSet(DSL.name(alias), this);
    }

    @Override
    public WingSet as(Name alias) {
        return new WingSet(alias, this);
    }

    @Override
    public WingSet as(Table<?> alias) {
        return new WingSet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WingSet rename(String name) {
        return new WingSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WingSet rename(Name name) {
        return new WingSet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WingSet rename(Table<?> name) {
        return new WingSet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WingSet where(Condition condition) {
        return new WingSet(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WingSet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WingSet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WingSet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WingSet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WingSet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WingSet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WingSet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WingSet whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WingSet whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
