/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables;


import de.nightara.discord.raidbot.model.Keys;
import de.nightara.discord.raidbot.model.Raidbot;
import de.nightara.discord.raidbot.model.tables.Boss.BossPath;
import de.nightara.discord.raidbot.model.tables.WingSet.WingSetPath;
import de.nightara.discord.raidbot.model.tables.records.WingRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Wing extends TableImpl<WingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raidbot.wing</code>
     */
    public static final Wing WING = new Wing();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WingRecord> getRecordType() {
        return WingRecord.class;
    }

    /**
     * The column <code>raidbot.wing.short_name</code>.
     */
    public final TableField<WingRecord, String> SHORT_NAME = createField(DSL.name("short_name"), SQLDataType.VARCHAR(5).nullable(false), this, "");

    /**
     * The column <code>raidbot.wing.name</code>.
     */
    public final TableField<WingRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Wing(Name alias, Table<WingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Wing(Name alias, Table<WingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>raidbot.wing</code> table reference
     */
    public Wing(String alias) {
        this(DSL.name(alias), WING);
    }

    /**
     * Create an aliased <code>raidbot.wing</code> table reference
     */
    public Wing(Name alias) {
        this(alias, WING);
    }

    /**
     * Create a <code>raidbot.wing</code> table reference
     */
    public Wing() {
        this(DSL.name("wing"), null);
    }

    public <O extends Record> Wing(Table<O> path, ForeignKey<O, WingRecord> childPath, InverseForeignKey<O, WingRecord> parentPath) {
        super(path, childPath, parentPath, WING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WingPath extends Wing implements Path<WingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WingPath(Table<O> path, ForeignKey<O, WingRecord> childPath, InverseForeignKey<O, WingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WingPath(Name alias, Table<WingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WingPath as(String alias) {
            return new WingPath(DSL.name(alias), this);
        }

        @Override
        public WingPath as(Name alias) {
            return new WingPath(alias, this);
        }

        @Override
        public WingPath as(Table<?> alias) {
            return new WingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Raidbot.RAIDBOT;
    }

    @Override
    public UniqueKey<WingRecord> getPrimaryKey() {
        return Keys.KEY_WING_PRIMARY;
    }

    private transient BossPath _boss;

    /**
     * Get the implicit to-many join path to the <code>raidbot.boss</code> table
     */
    public BossPath boss() {
        if (_boss == null)
            _boss = new BossPath(this, null, Keys.BOSS_WING_SHORT_NAME_FK.getInverseKey());

        return _boss;
    }

    private transient WingSetPath _wingSet;

    /**
     * Get the implicit to-many join path to the <code>raidbot.wing_set</code>
     * table
     */
    public WingSetPath wingSet() {
        if (_wingSet == null)
            _wingSet = new WingSetPath(this, null, Keys.WING_SET_WING_SHORT_NAME_FK.getInverseKey());

        return _wingSet;
    }

    @Override
    public Wing as(String alias) {
        return new Wing(DSL.name(alias), this);
    }

    @Override
    public Wing as(Name alias) {
        return new Wing(alias, this);
    }

    @Override
    public Wing as(Table<?> alias) {
        return new Wing(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Wing rename(String name) {
        return new Wing(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Wing rename(Name name) {
        return new Wing(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Wing rename(Table<?> name) {
        return new Wing(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Wing where(Condition condition) {
        return new Wing(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Wing where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Wing where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Wing where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Wing where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Wing where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Wing where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Wing where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Wing whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Wing whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
