/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables.records;


import de.nightara.discord.raidbot.model.tables.Boss;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BossRecord extends UpdatableRecordImpl<BossRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raidbot.boss.short_name</code>.
     */
    public void setShortName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>raidbot.boss.short_name</code>.
     */
    public String getShortName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>raidbot.boss.wing</code>.
     */
    public void setWing(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raidbot.boss.wing</code>.
     */
    public String getWing() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raidbot.boss.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raidbot.boss.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>raidbot.boss.after</code>.
     */
    public void setAfter(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raidbot.boss.after</code>.
     */
    public String getAfter() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BossRecord
     */
    public BossRecord() {
        super(Boss.BOSS);
    }

    /**
     * Create a detached, initialised BossRecord
     */
    public BossRecord(String shortName, String wing, String name, String after) {
        super(Boss.BOSS);

        setShortName(shortName);
        setWing(wing);
        setName(name);
        setAfter(after);
        resetTouchedOnNotNull();
    }
}
