/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables.records;


import de.nightara.discord.raidbot.model.tables.Role;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raidbot.role.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>raidbot.role.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>raidbot.role.boss</code>.
     */
    public void setBoss(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raidbot.role.boss</code>.
     */
    public String getBoss() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raidbot.role.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raidbot.role.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(UInteger id, String boss, String name) {
        super(Role.ROLE);

        setId(id);
        setBoss(boss);
        setName(name);
        resetTouchedOnNotNull();
    }
}
