/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables.records;


import de.nightara.discord.raidbot.model.tables.Run;

import java.time.LocalDate;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RunRecord extends UpdatableRecordImpl<RunRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raidbot.run.date</code>.
     */
    public void setDate(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>raidbot.run.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>raidbot.run.ordinal</code>.
     */
    public void setOrdinal(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>raidbot.run.ordinal</code>.
     */
    public UInteger getOrdinal() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>raidbot.run.wing</code>.
     */
    public void setWing(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raidbot.run.wing</code>.
     */
    public String getWing() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<LocalDate, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RunRecord
     */
    public RunRecord() {
        super(Run.RUN);
    }

    /**
     * Create a detached, initialised RunRecord
     */
    public RunRecord(LocalDate date, UInteger ordinal, String wing) {
        super(Run.RUN);

        setDate(date);
        setOrdinal(ordinal);
        setWing(wing);
        resetTouchedOnNotNull();
    }
}
