/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables.records;


import de.nightara.discord.raidbot.model.tables.Signup;

import java.time.LocalDate;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SignupRecord extends TableRecordImpl<SignupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raidbot.signup.date</code>.
     */
    public void setDate(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>raidbot.signup.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>raidbot.signup.role</code>.
     */
    public void setRole(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>raidbot.signup.role</code>.
     */
    public UInteger getRole() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>raidbot.signup.player</code>.
     */
    public void setPlayer(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>raidbot.signup.player</code>.
     */
    public Long getPlayer() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SignupRecord
     */
    public SignupRecord() {
        super(Signup.SIGNUP);
    }

    /**
     * Create a detached, initialised SignupRecord
     */
    public SignupRecord(LocalDate date, UInteger role, Long player) {
        super(Signup.SIGNUP);

        setDate(date);
        setRole(role);
        setPlayer(player);
        resetTouchedOnNotNull();
    }
}
