/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables.records;


import de.nightara.discord.raidbot.model.tables.Wing;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WingRecord extends UpdatableRecordImpl<WingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raidbot.wing.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>raidbot.wing.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>raidbot.wing.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raidbot.wing.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WingRecord
     */
    public WingRecord() {
        super(Wing.WING);
    }

    /**
     * Create a detached, initialised WingRecord
     */
    public WingRecord(String id, String name) {
        super(Wing.WING);

        setId(id);
        setName(name);
        resetTouchedOnNotNull();
    }
}
