/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model.tables.records;


import de.nightara.discord.raidbot.model.tables.WingSet;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WingSetRecord extends UpdatableRecordImpl<WingSetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>raidbot.wing_set.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>raidbot.wing_set.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>raidbot.wing_set.wing</code>.
     */
    public void setWing(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raidbot.wing_set.wing</code>.
     */
    public String getWing() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raidbot.wing_set.ordinal</code>.
     */
    public void setOrdinal(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>raidbot.wing_set.ordinal</code>.
     */
    public Integer getOrdinal() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WingSetRecord
     */
    public WingSetRecord() {
        super(WingSet.WING_SET);
    }

    /**
     * Create a detached, initialised WingSetRecord
     */
    public WingSetRecord(String name, String wing, Integer ordinal) {
        super(WingSet.WING_SET);

        setName(name);
        setWing(wing);
        setOrdinal(ordinal);
        resetTouchedOnNotNull();
    }
}
