/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model;


import de.nightara.discord.raidbot.model.tables.Signup;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in raidbot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SIGNUP_SIGNUP_RUN_DATE_WING_FK = Internal.createIndex(DSL.name("signup_run_date_wing_fk"), Signup.SIGNUP, new OrderField[] { Signup.SIGNUP.DATE }, false);
}
