/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model;


import de.nightara.discord.raidbot.model.tables.Boss;
import de.nightara.discord.raidbot.model.tables.Role;
import de.nightara.discord.raidbot.model.tables.Run;
import de.nightara.discord.raidbot.model.tables.Signup;
import de.nightara.discord.raidbot.model.tables.Wing;
import de.nightara.discord.raidbot.model.tables.records.BossRecord;
import de.nightara.discord.raidbot.model.tables.records.RoleRecord;
import de.nightara.discord.raidbot.model.tables.records.RunRecord;
import de.nightara.discord.raidbot.model.tables.records.SignupRecord;
import de.nightara.discord.raidbot.model.tables.records.WingRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * raidbot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BossRecord> KEY_BOSS_PRIMARY = Internal.createUniqueKey(Boss.BOSS, DSL.name("KEY_boss_PRIMARY"), new TableField[] { Boss.BOSS.ID }, true);
    public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = Internal.createUniqueKey(Role.ROLE, DSL.name("KEY_role_PRIMARY"), new TableField[] { Role.ROLE.ID }, true);
    public static final UniqueKey<RunRecord> KEY_RUN_PRIMARY = Internal.createUniqueKey(Run.RUN, DSL.name("KEY_run_PRIMARY"), new TableField[] { Run.RUN.DATE, Run.RUN.WING }, true);
    public static final UniqueKey<RunRecord> KEY_RUN_RUN_PK_2 = Internal.createUniqueKey(Run.RUN, DSL.name("KEY_run_run_pk_2"), new TableField[] { Run.RUN.ORDINAL, Run.RUN.DATE }, true);
    public static final UniqueKey<WingRecord> KEY_WING_PRIMARY = Internal.createUniqueKey(Wing.WING, DSL.name("KEY_wing_PRIMARY"), new TableField[] { Wing.WING.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BossRecord, BossRecord> BOSS_BOSS_ID_FK = Internal.createForeignKey(Boss.BOSS, DSL.name("boss_boss_id_fk"), new TableField[] { Boss.BOSS.AFTER }, Keys.KEY_BOSS_PRIMARY, new TableField[] { Boss.BOSS.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.CASCADE);
    public static final ForeignKey<BossRecord, WingRecord> BOSS_WING_ID_FK = Internal.createForeignKey(Boss.BOSS, DSL.name("boss_wing_id_fk"), new TableField[] { Boss.BOSS.WING }, Keys.KEY_WING_PRIMARY, new TableField[] { Wing.WING.ID }, true, ForeignKeyRule.SET_NULL, ForeignKeyRule.CASCADE);
    public static final ForeignKey<RoleRecord, BossRecord> ROLE_BOSS_ID_FK = Internal.createForeignKey(Role.ROLE, DSL.name("role_boss_id_fk"), new TableField[] { Role.ROLE.BOSS }, Keys.KEY_BOSS_PRIMARY, new TableField[] { Boss.BOSS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.CASCADE);
    public static final ForeignKey<RunRecord, WingRecord> RUN_WING_ID_FK = Internal.createForeignKey(Run.RUN, DSL.name("run_wing_id_fk"), new TableField[] { Run.RUN.WING }, Keys.KEY_WING_PRIMARY, new TableField[] { Wing.WING.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.CASCADE);
    public static final ForeignKey<SignupRecord, RoleRecord> SIGNUP_ROLE_ID_FK = Internal.createForeignKey(Signup.SIGNUP, DSL.name("signup_role_id_fk"), new TableField[] { Signup.SIGNUP.ROLE }, Keys.KEY_ROLE_PRIMARY, new TableField[] { Role.ROLE.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.CASCADE);
    public static final ForeignKey<SignupRecord, RunRecord> SIGNUP_RUN_DATE_FK = Internal.createForeignKey(Signup.SIGNUP, DSL.name("signup_run_date_fk"), new TableField[] { Signup.SIGNUP.DATE }, Keys.KEY_RUN_PRIMARY, new TableField[] { Run.RUN.DATE }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.CASCADE);
}
