/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model;


import de.nightara.discord.raidbot.model.tables.Boss;
import de.nightara.discord.raidbot.model.tables.Role;
import de.nightara.discord.raidbot.model.tables.Wing;
import de.nightara.discord.raidbot.model.tables.WingSet;
import de.nightara.discord.raidbot.model.tables.records.BossRecord;
import de.nightara.discord.raidbot.model.tables.records.RoleRecord;
import de.nightara.discord.raidbot.model.tables.records.WingRecord;
import de.nightara.discord.raidbot.model.tables.records.WingSetRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * raidbot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BossRecord> KEY_BOSS_PRIMARY = Internal.createUniqueKey(Boss.BOSS, DSL.name("KEY_boss_PRIMARY"), new TableField[] { Boss.BOSS.SHORT_NAME }, true);
    public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = Internal.createUniqueKey(Role.ROLE, DSL.name("KEY_role_PRIMARY"), new TableField[] { Role.ROLE.ID }, true);
    public static final UniqueKey<WingRecord> KEY_WING_PRIMARY = Internal.createUniqueKey(Wing.WING, DSL.name("KEY_wing_PRIMARY"), new TableField[] { Wing.WING.SHORT_NAME }, true);
    public static final UniqueKey<WingSetRecord> KEY_WING_SET_PRIMARY = Internal.createUniqueKey(WingSet.WING_SET, DSL.name("KEY_wing_set_PRIMARY"), new TableField[] { WingSet.WING_SET.NAME, WingSet.WING_SET.WING, WingSet.WING_SET.ORDINAL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BossRecord, BossRecord> BOSS_BOSS_SHORT_NAME_FK = Internal.createForeignKey(Boss.BOSS, DSL.name("boss_boss_short_name_fk"), new TableField[] { Boss.BOSS.AFTER }, Keys.KEY_BOSS_PRIMARY, new TableField[] { Boss.BOSS.SHORT_NAME }, true, ForeignKeyRule.RESTRICT, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<BossRecord, WingRecord> BOSS_WING_SHORT_NAME_FK = Internal.createForeignKey(Boss.BOSS, DSL.name("boss_wing_short_name_fk"), new TableField[] { Boss.BOSS.WING }, Keys.KEY_WING_PRIMARY, new TableField[] { Wing.WING.SHORT_NAME }, true, ForeignKeyRule.RESTRICT, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<RoleRecord, BossRecord> ROLE_BOSS_SHORT_NAME_FK = Internal.createForeignKey(Role.ROLE, DSL.name("role_boss_short_name_fk"), new TableField[] { Role.ROLE.BOSS }, Keys.KEY_BOSS_PRIMARY, new TableField[] { Boss.BOSS.SHORT_NAME }, true, ForeignKeyRule.RESTRICT, ForeignKeyRule.RESTRICT);
    public static final ForeignKey<WingSetRecord, WingRecord> WING_SET_WING_SHORT_NAME_FK = Internal.createForeignKey(WingSet.WING_SET, DSL.name("wing_set_wing_short_name_fk"), new TableField[] { WingSet.WING_SET.WING }, Keys.KEY_WING_PRIMARY, new TableField[] { Wing.WING.SHORT_NAME }, true, ForeignKeyRule.RESTRICT, ForeignKeyRule.RESTRICT);
}
