/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model;


import de.nightara.discord.raidbot.model.tables.Boss;
import de.nightara.discord.raidbot.model.tables.Role;
import de.nightara.discord.raidbot.model.tables.Run;
import de.nightara.discord.raidbot.model.tables.Signup;
import de.nightara.discord.raidbot.model.tables.Wing;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Raidbot extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>raidbot</code>
     */
    public static final Raidbot RAIDBOT = new Raidbot();

    /**
     * The table <code>raidbot.boss</code>.
     */
    public final Boss BOSS = Boss.BOSS;

    /**
     * The table <code>raidbot.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>raidbot.run</code>.
     */
    public final Run RUN = Run.RUN;

    /**
     * The table <code>raidbot.signup</code>.
     */
    public final Signup SIGNUP = Signup.SIGNUP;

    /**
     * The table <code>raidbot.wing</code>.
     */
    public final Wing WING = Wing.WING;

    /**
     * No further instances allowed
     */
    private Raidbot() {
        super(DSL.name("raidbot"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Boss.BOSS,
            Role.ROLE,
            Run.RUN,
            Signup.SIGNUP,
            Wing.WING
        );
    }
}
