/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model;


import de.nightara.discord.raidbot.model.tables.Boss;
import de.nightara.discord.raidbot.model.tables.Role;
import de.nightara.discord.raidbot.model.tables.Run;
import de.nightara.discord.raidbot.model.tables.Signup;
import de.nightara.discord.raidbot.model.tables.Wing;


/**
 * Convenience access to all tables in raidbot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>raidbot.boss</code>.
     */
    public static final Boss BOSS = Boss.BOSS;

    /**
     * The table <code>raidbot.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>raidbot.run</code>.
     */
    public static final Run RUN = Run.RUN;

    /**
     * The table <code>raidbot.signup</code>.
     */
    public static final Signup SIGNUP = Signup.SIGNUP;

    /**
     * The table <code>raidbot.wing</code>.
     */
    public static final Wing WING = Wing.WING;
}
