/*
 * This file is generated by jOOQ.
 */
package de.nightara.discord.raidbot.model;


import de.nightara.discord.raidbot.model.tables.Boss;
import de.nightara.discord.raidbot.model.tables.Role;
import de.nightara.discord.raidbot.model.tables.Wing;
import de.nightara.discord.raidbot.model.tables.WingSet;


/**
 * Convenience access to all tables in raidbot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>raidbot.boss</code>.
     */
    public static final Boss BOSS = Boss.BOSS;

    /**
     * The table <code>raidbot.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>raidbot.wing</code>.
     */
    public static final Wing WING = Wing.WING;

    /**
     * The table <code>raidbot.wing_set</code>.
     */
    public static final WingSet WING_SET = WingSet.WING_SET;
}
